# Generated by Django 2.1.5 on 2019-01-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reaction', models.IntegerField()),
                ('relation', models.IntegerField()),
                ('action', models.IntegerField()),
                ('person_1', models.IntegerField()),
                ('person_2', models.IntegerField()),
                ('moral', models.BooleanField()),
            ],
        ),
    ]
